name: Versioning
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main
    paths:
      - 'versioning.py'
      - '.github/workflows/version.yml'
env:
  CARGO_TERM_COLOR: always

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Git user
        run: |
          git config --global user.name ${{ github.repository_owner }}_action_bot
          git config --global user.email ${{ github.repository_owner }}@users.noreply.github.com
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Tag
        run: |
          python versioning.py
