name: Deploy Jupyter Book

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-test.txt
          python -m pip install -r requirements-book.txt

      - name: Build the book
        run: |
          jupyter-book build --all docs

      - name: Upload jupyter book
        uses: actions/upload-artifact@v3
        with:
          name: jupyterbook
          path: "docs/_build/html/"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-book]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name ${{ github.repository_owner }}_action_bot
          git config --global user.email ${{ github.repository_owner }}@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Tag
        run: |
          python versioning.py

      - name: Deploy
        run: |
          python ghp_setup.py
