# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_skip:
    if: ${{ startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: When Test is Skipped
    runs-on: ubuntu-latest
    steps:
      - name: Skip Test
        run: echo "Skip Test"

  test_py_latest_and_oldest:
    if: ${{ !startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: Test on Python Latest and Oldest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.13"]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Test Unit
        uses: ./.github/actions/test-unit
